var fruit = "banana";
console.log("Tests for equality and inequality with strings:");
console.log("Is fruit == 'banana'? I predict True.");
console.log(fruit == "banana");
console.log("Is fruit != 'apple'? I predict True.");
console.log(fruit != "apple");
var city = "New York";
console.log("Tests using the lower case function:");
console.log("Is city.toLowerCase() == 'new york'? I predict True.");
console.log(city.toLowerCase() == "new york");
console.log("Is city.toLowerCase() == 'new jersey'? I predict False.");
console.log(city.toLowerCase() == "new jersey");
var number = 10;
console.log("Numerical tests involving equality and inequality, greater than and less than, greater than or equal to, and less than or equal to:");
console.log("Is number == 10? I predict True.");
console.log(number == 10);
console.log("Is number != 5? I predict True.");
console.log(number != 5);
console.log("Is number > 5? I predict True.");
console.log(number > 5);
console.log("Is number < 20? I predict True.");
console.log(number < 20);
console.log("Is number >= 10? I predict True.");
console.log(number >= 10);
console.log("Is number <= 10? I predict True.");
console.log(number <= 10);
var x = 5;
var y = 15;
console.log("Tests using 'and' and 'or' operators:");
console.log("Is x > 0 and y < 10? I predict False");
